name: C/C++ CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make install
      run: make install
    - name: Upload the bin
      uses: actions/upload-artifact@v3
      with:
          name: ip2socks
          path: /usr/local/bin/ip2socks
